name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Echo message
      run: echo "Hi Vamsi! This is running on your Ubuntu. I repeat, your own Ubuntu!"
